on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

name: Build LaTeX document using xu-cheng's Action

jobs:
  build_latex:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: article.tex

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: xu_cheng_pdf
          path: article.pdf

