on:
  push:
  pull_request:

name: Build LaTeX document using dante-ev's Action

jobs:
  build_latex:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: article.tex

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: dante_ev_pdf
          path: article.pdf

