on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

name: Build LaTeX document using thomas-chauvet's Action

jobs:
  build_latex:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: latex2pdf
        uses: thomas-chauvet/latex2pdf-action@1.0.3
        with:
          main_latex_file: article.tex
          ctan_packages: amssymb latexsym amsmath

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: thomas_chauvet_pdf
          path: article.pdf

